project:
  type: website
  output-dir: docs

website: 
  title: "libertysmith.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: curriculumvitae.qmd
        text: Curriculum Vitae
      - href: project.qmd
        text: Project
      - text: Labs
        menu: 
          - href: Lab1.qmd
            text: Lab1
          - href: Lab2.qmd
            text: Lab2
      - text: Assignments
        menu: 
            - href: assignment1.qmd
              text: assignment1
            - href: litreview.qmd
              text: What's Changed in Nine Years?
            - href: assignment2.qmd
              text: assignment2
            - href: assignment3.qmd
              text: assignment3

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

