project:
  type: website
  output-dir: docs

website: 
  title: "Knowledge Mining 6323"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: research.qmd
        text: Research Project
      - href: curriculumvitae.qmd
        text: Curriculum Vitae
      - text: Labs
        menu: 
          - href: Lab1.qmd
            text: Lab1
          - href: Lab2.qmd
            text: Lab2
          - href: Lab3.qmd
            text: Lab3
      - text: Assignments
        menu: 
            - href: assignment1.qmd
              text: Drafting Hypotheses
            - href: litreview.qmd
              text: What's Changed in Nine Years? LitReview
            - href: assignment2.qmd
              text: Exploratory Data Analysis
            - href: assignment3.qmd
              text: Multinomial Logistic Regression

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

  
  

