# Liberty "Libby" Smith

[LinkedIn Page](www.linkedin.com/in/liberty-libby-smith-aa6257156)

## EDUCATION

**The University of Texas at Dallas,** *(M.S., Social Data Analytics and Research)* May 2024

**The University of Texas at Dallas,** *(Bachelor of Arts in Political Science)* May 2017

## BUSINESS EXPERIENCE

**Korea Economic Institute of America**, Washington, D.C., USA *(Economic Intern)* Sept 2018 - Jan 2019

\* Led and assisted in statistical research and writing published on "The Peninsula" -- think tank sponsored blog -- alongside legacy media journalists and diplomats. \* Collaborated with stakeholders, researched, gauged value of Korea-US foreign trade and social policy. Suggested policy development directions for greater equitable economic policies and criminology.

\* Wrote and edited social media content for organizational content promotion on Twitter and Facebook. Extended reach of viewership by 15%, engagement analysis utilizing SproutSocial and MailChimp metrics.

**Suitsupply**, Dallas, Texas, USA *(Web Sales and Customer Service Analyst)* Dec 2021 - Present

\* Promoted the adoption of new Salesforce practices and specialized features increasing productivity and reducing team burnout and turnover by 50%, leading to relative increase of 5-15% in gross monthly sales.

\* Facilitated trainings on retail policy implementation to improve the tracking, execution, reporting, release and management of Product Knowledge.

\* Optimized the critical and recurrent concerns by analyzing Salesforce CRMS client feedback, improved the overall consistency and user experience of customer service, significantly increasing the ratings from 3.8 to 4.2, thus reducing direct contact ratio from 15% to 9% in six months.

\* Ensured complete user journeys with relevant error handling and complete feedback loops considering UX principles, user behavior & tendencies improving the overall consistency and experience of the customer service lifecycle.

\* Earned the rating of 'Exceptional' for 2 consecutive years and recognized among the top 3 performers in the branch office.

## EXTRA-CURRICULAR ACTIVITIES

**Acts of Kindness at UTD --** \*Founder and Treasurer Fall 2014 - Spring 2016

\* Leading a team of 12 members, proposed budget, organized the Council events, led presentation of group selected topics to advocate awareness on campus, coordinated Acts of Kindness drives (services) that supported students struggling financially during exam weeks.

\* Promoted inter and intra-college participation by strategizing existing modes of communication, created online presence, and multiplied reach utilizing social media.

## ADDITIONAL INFORMATION

*Technical Skills*: MySQL, Python, R, HTML, CSS, React, Google Analytics, Adobe Analytics, SalesForce Admin, MS Project Professional, MS Office, Project Management, Product Management, ML and Statistical Data Analytics, probability modelling, research and brief writing.

*Languages:* Advanced English and Conversational Korean

*Eligibility*: U.S. Citizen Authorized to work in the United States
