# A Literature Review by Libby Smith

This is a comparative literature review between Leo Breiman's paper "Statistical Modeling: The Two Cultures" and Galit Shmueli's piece "To Explain or to Predict?"

### Comparative Approach - From 2001 to 2010, What's Changed?

In 2001, Berkeley professor Leo Breiman wrote a seminole paper in which he convincingly advocates for the growth of the algorithm culture over the data modeling culture due to the trade off between interpretability and accuracy. Breiman argues algorithmic culture is a different caliber that demands more focus. Understanding what happens in the black box is marginally less important than the potential of its applied knowledge. Thus, algorithmic processes are less discriminatory and enable better knowledge mining than data modeling. He provides several examples of how its methods often precede improved accuracy, relative to data modeling methods. Data modeling, reasoned Breiman, had become too limited by its underlying assumptions such as its demands for theoretical relationships and interpretability. How to improve efficiency, how to improve greenhouse gas emissions, how to detect extreme weather events, any outcome-oriented goals are - or were - the pressing reasons to re-prioritize the two cultures. 

9 years later, author of "To Explain or to Predict?" by Galit Schmueli brings an updated  perspective to the table. Both authors agree a cultural gap resulted in two distinct modeling rationales which has led to data modeling culture's narrowing breadth of knowledge extraction. In contrast to Breiman, he does not advocate for one culture's rigor or survival over the other. By the time of his publication, a significant number of practices shared between the two cultures are identifiable. Thus, the two are not as rigidly defined. For example, traces of model validity and use commonly interchangeable tools such as partitioning and visualization. However, the tools are worked in different fashions, as led by the a priori project needs. Though he agrees a considerable gap remains (in four aspects) between the two cultures, algorithm modeling has caught up or even supersedes data modeling's practicality in many regards. \

In fact, Schmeuli argues the bridge to divide the knowledge gap should go both ways. The use of algorithmic modeling techniques have earned their place in research science and should not be limited to the specific spaces already associated with it. The ultimate pursuit of science demands so. The innovative methods and growth of algorithmic culture improve upon data modeling practices and the reverse is also true. The underlying wisdom of data modeling has more knowledge to impart to the bleeding edge of algorithmic culture.  \

All in all, the two papers are emblematic of the state of affairs in their respective eras. The evolution of data science is a story about humans urgently adapting through iterative sciences with the singular goal of gaining useful knowledge. How "useful knowledge" is defined seems to largely hinge on how one values the scale between prediction and interpretability. 

1/31/2023 Libby Smith
