---
title: "EPPS 6323: Lab03"
author: "Libby Smith"
format: html
editor: visual
---

# Research Proposal

## A Criminology Study

Haley Puddy

Hoda Osama

Libby Smith

## Project Purpose & Literature:

The purpose of this study is to reaffirm and discover what risk and protective factors increase or decrease the likelihood of victimization among a large sample of college students. There is a wealth of knowledge in this area showing that mental health problems and engagement in risky behaviors, like partying, sex, alcohol usage, and drug usage,significantly increase one's likelihood of being victimized (Azimi & Daigle, 2021; Turanovic et al., 2018). Additionally, previous research has found social connectedness to be one of the strongest protective factors against victimization (McLoughlin et al., 2019; Kast et al., 2016). This research goes in line with social control and bond theories that argue that individuals are prevented from engaging in delinquency, and thus victimization, by having strong bonds to society, family, friends, and conventional activities (Hirschi, 1969). Literature is lacking, however, on protective factors related to overall health and propensity to make safer decisions. This study aims to contribute to the literature by reaffirming what is already clear about the risk and protective factors of victimization, as well as adding to the literature about additional protective factors that may be negatively associated with victimization. The results of this study have potential to build upon thewell-researched base on victimization and suggest new protective factors for other researchers to take a closer look at.

## Research Questions

### Main research questions:

1\. What risk factors increase the likelihood of victimization for college students?

2\. What protective factors decrease the likelihood of victimization for college students?

### Additional/secondaryresearch questions:

3\. Is making certain healthier and safer decisions negatively correlated to victimization?

4\. Is engaging in specific risky behaviors positively correlated to victimization?

5\. Does the data confirm social control/bond theory in reducing incidences of victimization?

## Knowledge Mining Methods:

Our analysis plan includes using secondary data collected from the largest known dataset on the health of college students calledThe American Health College Association-National College Health Assessment (ACHA-NCHA III). It is a nationally recognized research survey consisting of 52 items on college student's health habits, behaviors, and perceptions. The data used for this project will be from the Spring of 2022, where 69,131 U.S. college students from across the country participated and completed the survey. Descriptive statistics using t-tests and chi-squares will be used as well as logistic regression models to measure what risk and protective factors have a positive or negative effect on victimization. Additionally, interaction and moderation effects will be used to determine if any combination of risk or protective factors exacerbate the effects on victimization.

## Variables:

DV: Victimization (violent, sexual, IPV)--categorical

IV(s): Risk & Protective factors for victimization--categorical & continuous

Risk factors: Engagement in risky behaviors (sex, alcoholusage, partying, fighting, and drug usage)Mental health problems

Protective factors: Overall health, Healthy decision making, Social connectedness, Sleep health, Safe driving

Controls: race/ethnicity, relationship status, gender, age
