<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Libby Smith">

<title>Knowledge Mining 101 with Libby Smith – assignment6</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Knowledge Mining 101 with Libby Smith</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">About Me</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./research.html">Research Project</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Curriculumvitae.html">Curriculum Vitae</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="button" data-bs-toggle="dropdown" aria-expanded="false">Labs</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="./Lab1.html">
 <span class="dropdown-text">Lab1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Lab2.html">
 <span class="dropdown-text">Lab2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Lab3.html">
 <span class="dropdown-text">Lab3</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-assignments" role="button" data-bs-toggle="dropdown" aria-expanded="false">Assignments</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-assignments">    
        <li>
    <a class="dropdown-item" href="./assignment1.html">
 <span class="dropdown-text">Drafting Hypotheses</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./litreview.html">
 <span class="dropdown-text">What’s Changed in Nine Years? LitReview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assignment2.html">
 <span class="dropdown-text">Exploratory Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assignment3.html">
 <span class="dropdown-text">Multinomial Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./report.html">
 <span class="dropdown-text">DATA Profiling EDA Report</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assignment4.html">
 <span class="dropdown-text">Gentle Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assignment5.html">
 <span class="dropdown-text">Gentle Text Mining</span></a>
  </li>  
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#logit-models-with-teds-data" id="toc-logit-models-with-teds-data" class="nav-link active" data-scroll-target="#logit-models-with-teds-data">Logit Models with TEDS Data</a>
  <ul class="collapse">
  <li><a href="#assignment-6" id="toc-assignment-6" class="nav-link" data-scroll-target="#assignment-6">Assignment 6</a>
  <ul class="collapse">
  <li><a href="#are-voting-women-in-taiwan-more-or-less-likely-to-vote-for-candidate-tsai" id="toc-are-voting-women-in-taiwan-more-or-less-likely-to-vote-for-candidate-tsai" class="nav-link" data-scroll-target="#are-voting-women-in-taiwan-more-or-less-likely-to-vote-for-candidate-tsai">Are voting women in Taiwan more or less likely to vote for Candidate Tsai?</a></li>
  <li><a href="#including-party-id-and-other-demographic-variables" id="toc-including-party-id-and-other-demographic-variables" class="nav-link" data-scroll-target="#including-party-id-and-other-demographic-variables">Including party ID and other demographic variables</a></li>
  </ul></li>
  <li><a href="#adding-additional-inputs" id="toc-adding-additional-inputs" class="nav-link" data-scroll-target="#adding-additional-inputs">Adding additional inputs</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="logit-models-with-teds-data" class="level1">
<h1>Logit Models with TEDS Data</h1>
<section id="assignment-6" class="level2">
<h2 class="anchored" data-anchor-id="assignment-6">Assignment 6</h2>
<section id="are-voting-women-in-taiwan-more-or-less-likely-to-vote-for-candidate-tsai" class="level3">
<h3 class="anchored" data-anchor-id="are-voting-women-in-taiwan-more-or-less-likely-to-vote-for-candidate-tsai">Are voting women in Taiwan more or less likely to vote for Candidate Tsai?</h3>
<p>First let’s read in the data. Remember that male is coded as 0 and female as 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>TEDS_2016<span class="ot">&lt;-</span><span class="fu">read_stata</span>(<span class="st">"https://github.com/datageneration/home/blob/master/DataProgramming/data/TEDS_2016.dta?raw=true"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we do a simple logistic regression</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>glm.vt <span class="ot">&lt;-</span> <span class="fu">glm</span>(votetsai<span class="sc">~</span>female, <span class="at">data =</span> TEDS_2016, <span class="at">family =</span> binomial)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm.vt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = votetsai ~ female, family = binomial, data = TEDS_2016)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.4180  -1.3889   0.9546   0.9797   0.9797  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  0.54971    0.08245   6.667 2.61e-11 ***
female      -0.06517    0.11644  -0.560    0.576    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1666.5  on 1260  degrees of freedom
Residual deviance: 1666.2  on 1259  degrees of freedom
  (429 observations deleted due to missingness)
AIC: 1670.2

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(glm.vt, <span class="at">level =</span> .<span class="dv">05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                 47.5 %      52.5 %
(Intercept)  0.54454587  0.55488636
female      -0.07247489 -0.05787115</code></pre>
</div>
</div>
<p>The logistic regression model examines the relationship between gender (female or male) and polling for Tsai in the 2016 Taiwan presidential election. The results indicated that gender is not a significant predictor of voting behavior, as the coefficient for female was negative but not statistically significant (Estimate = -0.065, SE = 0.116, p = 0.58). The intercept was statistically significant (Estimate = 0.55, SE = 0.082, p &lt; 0.001), suggesting that the odds of voting for Tsai are significantly different from zero. The model has a good fit, as indicated by a non-significant residual deviance (1666.2 on 1259 degrees of freedom) and a relatively low AIC (1670.2). These findings suggest that gender did not play a significant role in determining voting behavior in the 2016 Taiwan presidential election. Thus we cannot reject the null hypothesis, instead we reject the alternate hypothesis. Doing further model fit tests would be redundant.</p>
<p>Additionally, the model cannot be considered correctly specified for this social dynamic as it only has one variable. It does not have the power to have any practical use, or generalizability. Gender is often a control variable that allows social science researchers to more accurately assess causal relationships so that observed changes in the dependent variable can be attributed to the independent variables of interest.</p>
</section>
<section id="including-party-id-and-other-demographic-variables" class="level3">
<h3 class="anchored" data-anchor-id="including-party-id-and-other-demographic-variables">Including party ID and other demographic variables</h3>
<p>To examine the dynamics that influence Tsai voters and review how gender changes with added non-control and control variables we select to add the Kuo-min Tang and Democratic Progressive Party membership, age, education, and income in the 2016 Taiwan presidential election.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>glm.vt2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(votetsai<span class="sc">~</span>female<span class="sc">+</span>KMT<span class="sc">+</span>DPP<span class="sc">+</span>age<span class="sc">+</span>edu<span class="sc">+</span>income, <span class="at">data =</span> TEDS_2016, <span class="at">family =</span> binomial)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm.vt2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = votetsai ~ female + KMT + DPP + age + edu + income, 
    family = binomial, data = TEDS_2016)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.7360  -0.3673   0.2408   0.2946   2.5408  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.618640   0.592084   2.734  0.00626 ** 
female       0.047406   0.177403   0.267  0.78930    
KMT         -3.156273   0.250360 -12.607  &lt; 2e-16 ***
DPP          2.888943   0.267968  10.781  &lt; 2e-16 ***
age         -0.011808   0.007164  -1.648  0.09931 .  
edu         -0.184604   0.083102  -2.221  0.02632 *  
income       0.013727   0.034382   0.399  0.68971    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1661.76  on 1256  degrees of freedom
Residual deviance:  836.15  on 1250  degrees of freedom
  (433 observations deleted due to missingness)
AIC: 850.15

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(glm.vt2, <span class="at">level =</span> .<span class="dv">05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                 47.5 %      52.5 %
(Intercept)  1.58152200  1.65577911
female       0.03628233  0.05853110
KMT         -3.17200275 -3.14059985
DPP          2.87217346  2.90578596
age         -0.01225681 -0.01135835
edu         -0.18981629 -0.17939393
income       0.01157144  0.01588349</code></pre>
</div>
</div>
<p>The results indicated that gender is again not a significant predictor of voting behavior, as the coefficient for female flipped directionally and is still not statistically significant (Estimate = .047, SE = 0.177, p = 0.79). This is to be expected with a control variable in this context. Although not all inputs are found to be statistically significant, this model is an improvement and more parsimonious than the last due to the capturing of more reliable and interpretable data in the model. The partisan elements of the model are the most relevant independent variables that are not control groups. They say something meaningful about the outputs and are not included simply to isolate causal relationships. We are interested in their potential for a causal relationship with voting for Tsai. With every one unit increase of KMT affiliation, the log odds for voting for Tsai decrease by 3.16 units, holding all other inputs constant. With every one unit increase of DPP affiliation, the log odds for voting for Tsai increase by 2.89 units, holding all other inputs constant. The Aikike Information Criterion (AIC) which is one test to assess goodness of fit for Maximum Likelihood methods. AIC is lower for the second model which indicates it is a more parsimonious model than the simple logistic model from above. Although we can reject the null hypothesis that all input coefficients are 0, let’s see if additional variables will improve the next model.</p>
</section>
</section>
<section id="adding-additional-inputs" class="level2">
<h2 class="anchored" data-anchor-id="adding-additional-inputs">Adding additional inputs</h2>
<p>This time around, we will add relevant variables Independence, Econ_worse, Govt_dont_care, Minnan_father, Mainland_father, and Taiwanese to the model to test the relevance of controls and see if we can improve parsimony.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>glm.vt3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(votetsai<span class="sc">~</span>female<span class="sc">+</span>KMT<span class="sc">+</span>DPP<span class="sc">+</span>age<span class="sc">+</span>edu<span class="sc">+</span>income<span class="sc">+</span>Independence<span class="sc">+</span>Econ_worse<span class="sc">+</span>Govt_dont_care<span class="sc">+</span>Minnan_father<span class="sc">+</span>Mainland_father<span class="sc">+</span>Taiwanese, <span class="at">data =</span> TEDS_2016, <span class="at">family =</span> binomial)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm.vt3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = votetsai ~ female + KMT + DPP + age + edu + income + 
    Independence + Econ_worse + Govt_dont_care + Minnan_father + 
    Mainland_father + Taiwanese, family = binomial, data = TEDS_2016)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-3.1060  -0.3143   0.1744   0.3975   2.7917  

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -0.015976   0.679780  -0.024  0.98125    
female          -0.097996   0.189840  -0.516  0.60571    
KMT             -2.922246   0.259333 -11.268  &lt; 2e-16 ***
DPP              2.468855   0.275350   8.966  &lt; 2e-16 ***
age              0.003287   0.007884   0.417  0.67672    
edu             -0.092110   0.090119  -1.022  0.30674    
income           0.021771   0.036406   0.598  0.54984    
Independence     1.020953   0.251776   4.055 5.01e-05 ***
Econ_worse       0.310462   0.189100   1.642  0.10063    
Govt_dont_care  -0.014295   0.188765  -0.076  0.93964    
Minnan_father   -0.247650   0.253921  -0.975  0.32941    
Mainland_father -1.089332   0.396822  -2.745  0.00605 ** 
Taiwanese        0.909019   0.198930   4.570 4.89e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1661.76  on 1256  degrees of freedom
Residual deviance:  767.13  on 1244  degrees of freedom
  (433 observations deleted due to missingness)
AIC: 793.13

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(glm.vt3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                      2.5 %      97.5 %
(Intercept)     -1.34907937  1.31941711
female          -0.47124062  0.27391576
KMT             -3.45528242 -2.43461354
DPP              1.95495861  3.04056515
age             -0.01215092  0.01879865
edu             -0.26959631  0.08413584
income          -0.04949786  0.09339649
Independence     0.53600565  1.52504796
Econ_worse      -0.06101614  0.68118586
Govt_dont_care  -0.38550594  0.35542171
Minnan_father   -0.75192328  0.24518150
Mainland_father -1.88219179 -0.32337514
Taiwanese        0.51930794  1.30000820</code></pre>
</div>
</div>
<p>The results indicated that gender is again not a significant predictor of voting behavior, as the coefficient for female flipped directionally and is still not statistically significant (Estimate = -.10, SE = 0.190, p = 0.98). Similarly, other demo graphical control inputs such as age, have a similar relevance. Party membership remains the strongest correlations for/against votes for Tsai. The addition of 6 new inputs netted one additional input of statistical significance than the previous model. The AIC is also reduced from the previous model. For both of these reasons, this model is so far the most parsimonious of all three. Due to the non-zero coefficients in the model and their significant p-values, we can reject the null hypothesis that no input’s influence is exerted on the output.</p>
<p>We can do further tests to confirm beyond the AIC comparisons such as the Hosmer-Lemeshow Fit Test or the Pearsons Statistics to test the including or removal of variables to find the most parsimonious model from the data.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>